# Site settings
title: born2scan
description: >
  born2scan Team

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://born2scan.run" # the base hostname & protocol for your site

author:
  fullname: born2scan Team
  github: born2scan

# Syntax highlighting (if not set, defaults to solarized-dark in 'styling.html')
highlightstyle: 'atom-one-dark'
styles: [a11y-dark, a11y-light, agate, androidstudio, an-old-hope, arduino-light, arta, ascetic, atelier-cave-dark, atelier-cave-light, atelier-dune-dark, atelier-dune-light, atelier-estuary-dark, atelier-estuary-light, atelier-forest-dark, atelier-forest-light, atelier-heath-dark, atelier-heath-light, atelier-lakeside-dark, atelier-lakeside-light, atelier-plateau-dark, atelier-plateau-light, atelier-savanna-dark, atelier-savanna-light, atelier-seaside-dark, atelier-seaside-light, atelier-sulphurpool-dark, atelier-sulphurpool-light, atom-one-dark, atom-one-dark-reasonable, atom-one-light, brown-paper, codepen-embed, color-brewer, darcula, dark, default, docco, dracula, far, foundation, github, github-gist, gml, googlecode, gradient-dark, gradient-light, grayscale, gruvbox-dark, gruvbox-light, hopscotch, hybrid, idea, ir-black, isbl-editor-dark, isbl-editor-light, kimbie.dark, kimbie.light, lightfair, lioshi, magula, mono-blue, monokai, monokai-sublime, night-owl, nnfx, nnfx-dark, nord, obsidian, ocean, paraiso-dark, paraiso-light, pojoaque, purebasic, qtcreator_dark, qtcreator_light, railscasts, rainbow, routeros, school-book, shades-of-purple, solarized-dark, solarized-light, srcery, stackoverflow-dark, stackoverflow-light, sunburst, tomorrow, tomorrow-night, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night-eighties, vs, vs2015, xcode, xt256, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown
kramdown:
  auto_ids: true # Custom settings for anchor_links
  math_engine: mathjax
  syntax_highlighter_opts:
    disable: true
